Remove subset type within Union
* `Union[A, B]` is a subset of `Union[A, B, C]`, which is the case for
the Parameter/Artifact/Dict types used for the inputs type, which was
causing mypy complaints - we don't need to use Sequence if we remove the
unnecessary component of the Union:

```
$ mypy examples/input_output.py
examples/input_output.py:16: error: Argument "inputs" to "Task" has incompatible type "List[Parameter]"; expected "Union[List[Union[Parameter, Artifact]], List[Union[Parameter, Artifact, Dict[str, Any]]], Dict[str, Any], None]"  [arg-type]
examples/input_output.py:16: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
examples/input_output.py:16: note: Consider using "Sequence" instead, which is covariant
```

Signed-off-by: Elliot Gunton <egunton@bloomberg.net>