Fix issues with exporting scripts with resources (#554)
This looks like a possible typo. I don't believe
`self._build_resources(),` should be passed to the ModelTemplate
constructor as resource.

The following code currently fails with a pydantic error, but works
correctly with the constructor argument removed.

```python
from hera.workflows import Task, Workflow, Resources, script


@script(resources=Resources(memory_request='5Gi'))
def task_with_lots_of_memory():
    print('ok')


with Workflow(
    name="test",
    entrypoint='main',
) as test_wf:

    with DAG(name='main', ) as main:
        this_should_pass: Task = task_with_lots_of_memory()

if __name__ == "__main__":
    print(test_wf.to_yaml())
```

Error:
```
pydantic.error_wrappers.ValidationError: 1 validation error for Template
resource -> action
  field required (type=value_error.missing)
```

Signed-off-by: jp <jplikesbikes@gmail.com>