Set status=None if any status field is None (#686)
**Pull Request Checklist**
- [x] Fixes #<!--issue number goes here--> Related to #679
- [ ] Tests added
- [ ] Documentation/examples added
- [x] [Good commit messages](https://cbea.ms/git-commit/) and/or PR
title

**Description of PR**

I kept running into the following error message when I would try to
update my CronWorkflow.

```py
pydantic.error_wrappers.ValidationError: 2 validation errors for CronWorkflow
status -> active
  none is not an allowed value (type=type_error.none.not_allowed)
status -> lastScheduledTime
  none is not an allowed value (type=type_error.none.not_allowed)
```

Unfortunately this error would only appear if at least workflow has been
created. Comparing the two models, `WorkflowStatus` `CronWorkflowStatus`
in v1alpha1.py, it seems that the former has all of it's fields set to
optional and it makes sense that the same should apply to
`CronWorkflowStatus`; this is what this PR does.

With this fix, I was able to update my CronWorkflows regardless of the
current status.

---------

Signed-off-by: iameskild <eskild.eriksen122@gmail.com>